/**
 * This file is auto-generated by the Supabase CLI.
 * Run: supabase gen types typescript --local > apps/web/src/types/database.ts
 *
 * Do not edit manually.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Full type definitions will be generated once the database schema is applied.
// Placeholder exported so the app compiles before schema is ready.
export interface Database {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
